### ISSUE TITLE
[tutorial-era5-land-floods-precipitation-anomaly-in-greece]: Unnecessary data downloaded

### ISSUE THREAD

**Issue by clausmichele** [SercoSPA/DESP-UserWorkflowService-Templates#44]
The notebook [tutorial-era5-land-floods-precipitation-anomaly-in-greece](https://github.com/SercoSPA/DESP-UserWorkflowService-Templates/blob/main/EarthDataHub/tutorial-era5-land-floods-precipitation-anomaly-in-greece.ipynb) is selecting ~2.5GB of data instead of ~0.5GB as shown in the tutorial here https://earthdatahub.destine.eu/tutorials/tutorial-era5-land-floods-precipitation-anomaly-in-greece (which is the current notebook output). This would use many unnecessary credits to download the data.

![image](https://github.com/user-attachments/assets/b4acbf8b-d910-4f10-bcad-80cc238b21db)

Additionally, the `tp_greece_september_computed` is being computed (downloaded) to visualize only a single date. I would suggest to trigger the computation later, after the data reduction step, to download only the strictly necessary data and reduce the necessary resources. This would reduce the downloaded data to:
![image](https://github.com/user-attachments/assets/0017cc6a-7ca1-470c-bbe1-cb372b904954)

Similarly, in the **Cumulative precipitation: 2023 vs 1991-2022** section, the full time series is being downloaded, even if only the data from 1990 onwards is being used for the plot. We can again reduce the selected data before downloading, reducing the amount from:
![image](https://github.com/user-attachments/assets/afd087c1-e93a-473e-981c-270c5e436c43)

to:

![image](https://github.com/user-attachments/assets/7c2a3db3-ecb2-42a8-ac8f-3aecd78dce09)

I will open a PR to fix the mentioned issues.

Edit: PR here https://github.com/SercoSPA/DESP-UserWorkflowService-Templates/pull/45

**Comment by nicolamasotti** [comment]
Hi @clausmichele, thank you for your interest in Earth Data Hub! 

Indeed, there is still space for optimisation in this tutorial. We can easily target only the 1991-2023 time period. However notice that at least the 1991-2023 September data is later used for building the confrontation plot, which makes the initial `compute()` still useful. 

Also, be carful when using the `estimate_download_size()` function. This will only work when applied to an "unprocessed" subset of the original dataset, In other words, you need to use it BEFORE any reduction operation. You can refer to the documentation inside the function for this. What truly matters is the number of chunks that Dask must download to execute the code, not the size of the reduced data (which is still important for memory issues).

We will update the tutorial according to your suggestion. Nice catch!

**Comment by clausmichele** [comment]
Hi @nicolamasotti, thanks for the quick feedback:

> Indeed, there is still space for optimisation in this tutorial. We can easily target only the 1991-2023 time period. However notice that the 1991-2023 September data is later used for building the confrontation plot, which makes the initial `compute()` still useful.

True, in fact I suggest to `.compute()` only the data within that period and not of the whole period from 1950, which is not used. I forgot to use the computed xarray in the plot, I will fix it in the PR.

> Also, be carful when using the `estimate_download_size()` function. This will only work when applied to an "unprocessed" subset of the original dataset, In other words, you need to use it BEFORE any reduction operation. You can refer to the documentation inside the function for this. What truly matters is the number of chunks that Dask must download to execute the code, not the size of the reduced data (which is still important for memory issues).

Yeah, I didn't notice the difference because the following calls give the same result, since the chunk number doesn't change:

```python
import costing
costing.estimate_download_size(tp, tp_greece_september.sel(valid_time=["2023-09-06", "2023-09-07"]))
costing.estimate_download_size(tp, tp_greece_september.sel(valid_time=["2023-09-06", "2023-09-07"]).sum("valid_time"))
```

![image](https://github.com/user-attachments/assets/e21d7fba-a91f-4ea8-a019-4b46da9b39d5)

**Comment by gcipolletta** [comment]
Dear @clausmichele thank you for your interest in the DestinE Platform services! We greatly appreciate your contributions on the tutorials of EDH
Kindly advice us when you are done with the commits and so that we can review the contribution 

Kind regards
Gaia

**Comment by clausmichele** [comment]
Hi @gcipolletta, I'm done!

**Comment by gcipolletta** [comment]
Dear @clausmichele 
Thank you for your contribution and suggestion, it is greatly appreciated! However, after an internal review, we cannot accept it in its current form due to some technical details related to the behavior of the service itself that have not been fully addressed.
We will, however, take your suggestion into account for the next notebook release.
Thank you once again for your interest and kind cooperation!

**Comment by gcipolletta** [comment]
Dear @clausmichele 

I wanted to let you know that we have recently accepted your commits to the Earth Data Hub notebook, incorporating the optimizations you suggested. Please feel free to test the new features that have been implemented! 
Thank you again for your valuable input and contributions to the DestinE platform services! 

Kind regards
